export const balloonsInfo = [["Blackmaws", [,], 2, 1, "/images/balloons/blackmaws.jpg", "jeet"],
                    ["Colossus", [,], 3, 0, "/images/balloons/colossus.jpg", "jeet"],
                    ["Balefire Flatland", [,], 4, 0, "/images/balloons/balefireflatland.jpg", "jeet"],
                    ["Fuel Veins", [,], 2, 0, "/images/balloons/fuelveins.jpg", "jeet"],
                    ["Dry Gustie", [,], 4, 0, "/images/balloons/drygustie.jpg", "gutgash"],
                    ["Parch Moon", [,], 1, 1, "/images/balloons/parchmoon.jpg", "gutgash"],
                    ["Grit Canyons", [,], 1, 1, "/images/balloons/gritcanyons.jpg", "gutgash"],
                    ["Chalkies", [,], 1, 0, "/images/balloons/chalkies.jpg", "gutgash"],
                    ["Cadavanaugh", [,], 1, 1, "/images/balloons/cadavanaugh.jpg", "gutgash"],
                    ["Reek Hills", [,], 1, 0, "/images/balloons/reekhills.jpg", "gutgash"],
                    ["Knit Sack", [,], 1, 0, "/images/balloons/knitsack.jpg", "pinkeye"],
                    ["Wailing Wind", [,], 2, 1, "/images/balloons/wailingwind.jpg", "pinkeye"],
                    ["Grandrise", [,], 2, 0, "/images/balloons/grandrise.jpg", "pinkeye"],
                    ["The Heights", [,], 4, 1, "/images/balloons/theheights.jpg", "pinkeye"],
                    ["Rot 'N' Rusties", [,], 2, 0, "/images/balloons/rotnrusties.jpg", "pinkeye"],
                    ["The Dumps", [,], 1, 0, "/images/balloons/dumpballoon.jpg", "thedumps"],
                                     ];