export const balloonsInfo = [["Blackmaws", [,], 2, 1, "/images/balloons/blackmaws.jpg", "jeet"],
                    ["Colossus", [,], 3, 0, "/images/balloons/colossus.jpg", "jeet"],
                    ["Balefire Flatland", [,], 4, 0, "/images/balloons/balefireflatland.jpg", "jeet"],
                    ["Fuel Veins", [,], 2, 0, "/images/balloons/fuelveins.jpg", "jeet"],
                    ["Dry Gustie", [,], 4, 0, "/images/balloons/drygustie.jpg", "gutgash"],
                    ["Parch Moon", [,], 1, 1, "/images/balloons/parchmoon.jpg", "gutgash"],
                    ["Grit Canyons", [,], 1, 1, "/images/balloons/gritcanyons.jpg", "gutgash"],
                    ["Chalkies", [,], 1, 0, "/images/balloons/chalkies.jpg", "gutgash"],
                    ["Cadavanaugh", [,], 1, 1, "/images/balloons/cadavanaugh.jpg", "gutgash"],
                    ["Reek Hills", [,], 1, 0, "/images/balloons/reekhills.jpg", "gutgash"],
                    ["Knit Sack", [,], 1, 0, "/images/balloons/knitsack.jpg", "pinkeye"],
                    ["Wailing Wind", [,], 2, 1, "/images/balloons/wailingwind.jpg", "pinkeye"],
                    ["Grandrise", [,], 2, 0, "/images/balloons/grandrise.jpg", "pinkeye"],
                    ["The Heights", [,], 4, 1, "/images/balloons/theheights.jpg", "pinkeye"],
                    ["Rot 'N' Rusties", [,], 2, 0, "/images/balloons/rotnrusties.jpg", "pinkeye"],
                    ["The Dumps", [,], 1, 0, "/images/balloons/dumpballoon.jpg", "thedumps"],
                                     ];

export const campsInfo = [["Undertow", "Outer Graves", "/locations/camps/undertow.html", [3980, 300], "Pump", "jeet"],
                 ["The Edge", "Blackmaws", "/locations/camps/theedge.html", [3310, 620], "Pump", "jeet"],
                 ["Bonecrack", "Blackmaws", "/locations/camps/bonecrack.html", [3560, 870], "Pump", "jeet"],
                 ["Gas Works", "Blackmaws", "/locations/camps/gasworks.html", [3010, 970], "Top Dog", "jeet"],
                 ["Rust Bird", "Colossus", "/locations/camps/rustbird.html", [4260, 1220], "Legion", "jeet"],
                 ["Great Watcher", "Colossus", "/locations/camps/greatwatcher.html", [4440, 1670], "Top Dog", "jeet"],
                 ["The Dredges", "Balefire Flatland", "/locations/camps/thedredges.html", [3410, 1310], "Tanks", "jeet"],
                 ["Sand Sifter", "Balefire Flatland", "/locations/camps/sandsifter.html", [3020, 1650], "Tanks", "jeet"],
                 ["Hollow Point", "Balefire Flatland", "/locations/camps/hollowpoint.html", [3510, 2180], "Pump", "jeet"],
                 ["Wreck Hill", "Dry Gustie", "/locations/camps/wreckhill.html", [3840, 1730], "Tanks", "jeet"],
                 ["Ironclad", "Dry Gustie", "/locations/camps/ironclad.html", [3740, 2580], "Legion", "jeet"],
                 ["The Pipes", "Fuel Veins", "/locations/camps/thepipes.html", [3030, 2300], "Pump", "jeet"],
                 ["Black Sands", "Fuel Veins", "/locations/camps/blacksands.html", [3300, 2710], "Pump", "jeet"],
                 ["Gob Stone", "Grit Canyons", "/locations/camps/gobstone.html", [2440, 670], "Pump", "gutgash"],
                 ["Black Cove", "Grit Canyons", "/locations/camps/blackcove.html", [2200, 1380], "Pump", "gutgash"],
                 ["Overlook", "Grit Canyons", "/locations/camps/overlook.html", [2550, 1610], "Tanks", "gutgash"],
                 ["Rook Nest", "Parch Moon", "/locations/camps/rooknest.html", [1750, 890], "Tanks", "gutgash"],
                 ["Storm Shelter", "Reek Hills ", "/locations/camps/stormshelter.html", [960, 970], "Tanks", "gutgash"],
                 ["Scorched Sands", "Reek Hills", "/locations/camps/scorchedsands.html", [590, 1310], "Tanks", "gutgash"], 
                 ["Proving Grounds", "Cadavanaugh", "/locations/camps/provinggrounds.html", [1220, 1660], "Top Dog", "gutgash"], 
                 ["Blood Ridge", "Cadavanaugh", "/locations/camps/bloodridge.html", [700, 2020], "Pump", "gutgash"], 
                 ["Large Blade", "Chalkies", "/locations/camps/largeblade.html", [2310, 1940], "Top Dog", "gutgash"], 
                 ["Jugular Canyon", "Chalkies", "/locations/camps/jugularcanyon.html", [1800, 2010], "Legion", "gutgash"], 
                 ["Blood Beach", "Chalkies", "/locations/camps/bloodbeach.html", [1610, 2670], "Tanks", "gutgash"],  
                 ["Finger Peak", "Chalkies", "/locations/camps/fingerpeak.html", [1190, 2550], "Legion", "gutgash"], 
                 ["Havoc Point", "Knit Sack", "/locations/camps/havocpoint.html", [1820, 3300], "Pump", "pinkeye"], 
                 ["Grave Bridge", "Knit Sack", "/locations/camps/gravebridge.html", [2270, 3430], "Legion", "pinkeye"], 
                 ["Dead End", "Rot 'N' Rusties", "/locations/camps/deadend.html", [2830, 3600], "Tanks", "pinkeye"], 
                 ["Tyrant's Lash", "Rot 'N' Rusties", "/locations/camps/tyrantslash.html", [2580, 4020], "Top Dog", "pinkeye"], 
                 ["Twin Sisters", "Rot 'N' Rusties", "/locations/camps/twinsisters.html", [2430, 4420], "Legion", "pinkeye"], 
                 ["Stonehold", "Wailing Wind", "/locations/camps/stonehold.html", [1270, 3470], "Pump", "pinkeye"], 
                 ["Hell's Grill", "Wailing Wind", "/locations/camps/hellsgrill.html", [940, 4000], "Tanks", "pinkeye"], 
                 ["Old Hole", "Grandrise", "/locations/camps/oldhole.html", [500, 4150], "Pump", "pinkeye"], 
                 ["The Drop", "Grandrise", "/locations/camps/thedrop.html", [330, 4700], "Top Dog", "pinkeye"], 
                 ["The Choke", "Grandrise", "/locations/camps/thechoke.html", [1390, 5110], "Tanks", "pinkeye"], 
                 ["Skull Top", "The Heights", "/locations/camps/skulltop.html", [1570, 4360], "Tanks", "pinkeye"], 
                 ["Wheel Greaser", "The Heights", "/locations/camps/wheelgreaser.html", [2620, 5480], "Pump", "pinkeye"], 
                                     ];

export const deathracesInfo = [["Broken Pipes", "Blackmaws", "/locations/camps/brokenpipes.html", [3060, 700], "Scatter Run", "jeet"],
                      ["Corner Cut", "Colossus", "/locations/camps/cornercut.html", [4020, 950], "Barrel Bash", "jeet"],
                      ["Valley of Dust", "Dry Gustie", "/locations/camps/valleyofdust.html", [4340, 2790], "Time Bomb", "jeet"],
                      ["Crazy Racy", "Fuel Veins", "/locations/camps/crazyracy.html", [2780, 2550], "Barrel Bash", "jeet"],
                      ["Heat Haze", "Fuel Veins", "/locations/camps/heathaze.html", [3850, 3150], "Scatter Run", "jeet"],
                      ["Craggy Crew", "Grit Canyons", "/locations/camps/craggycrew.html", [2740, 510], "Scatter Run", "gutgash"],
                      ["Summit of the Mighty", "Parch Moon", "/locations/camps/summitofthemighty.html", [1970, 320], "Barrel Bash", "gutgash"],
                      ["Neck Snappin'", "Reek Hills", "/locations/camps/necksnappin.html", [280, 1210], "Scatter Run", "gutgash"],
                      ["Pothole Ridge", "Cadavanaugh", "/locations/camps/potholeridge.html", [950,  2500], "Time Bomb", "gutgash"],
                      ["Buckle Down", "Chalkies", "/locations/camps/buckledown.html", [1590, 2390], "Barrel Bash", "gutgash"],
                      ["Even Rip", "Knit Sack", "/locations/camps/evenrip.html", [2730, 3120], "Time Bomb", "pinkeye"],
                      ["The Reconvene", "Wailing Wind", "/locations/camps/wailingwind.html", [790, 4030], "Scatter Run", "pinkeye"],
                      ["Barreling-Barrows", "Grandrise", "/locations/camps/barrelingbarrows.html", [620, 5200], "Barrel Bash", "pinkeye"],
                      ["Mortal Bite", "The Heights", "/locations/camps/mortalbite.html", [1570, 5210], "Barrel Bash", "pinkeye"],
                      ["Tricky Pass", "Rot 'N' Rusties", "/locations/camps/trickypass.html", [3070, 4240], "Scatter Run", "pinkeye"],                      
                                     ];

export const minefieldsInfo = [["East Blackmaws", [,], "/images/minefields/eastblackmawsminefield.jpg", "jeet"],
                      ["West Blackmaws", [,], "/images/minefields/westblackmawsminefield.jpg", "jeet"],
                      ["North Colossus", [,], "/images/minefields/northcolossusminefield.jpg", "jeet"],
                      ["NW Balefire Flatland", [,], "/images/minefields/nwbalefireflatlandminefield.jpg", "jeet"],
                      ["North Balefire Flatland", [,], "/images/minefields/northbalefireflatlandminefield.jpg", "jeet"],
                      ["West Dry Gustie", [,], "/images/minefields/westdrygustieminefield.jpg", "jeet"],
                      ["North Dry Gustie", [,], "/images/minefields/northdrygustieminefield.jpg", "jeet"],
                      ["Central Fuel Veins", [,], "/images/minefields/centralfuelveinsminefield.jpg", "jeet"],
                      ["NE Fuel Veins ", [,], "/images/minefields/nefuelveinsminefield.jpg", "jeet"],
                      ["North Grit Canyons", [,], "/images/minefields/northgritcanyonsminefield.jpg", "gutgash"],
                      ["South Grit Canyons ", [,], "/images/minefields/southgritcanyonsminefield.jpg", "gutgash"],
                      ["Central Parch Moon", [,], "/images/minefields/centralparchmoonminefield.jpg", "gutgash"],
                      ["North Parch Moon", [,], "/images/minefields/northparchmoonminefield.jpg", "gutgash"],
                      ["East Reek Hills", [,], "/images/minefields/eastreekhillsminefield.jpg", "gutgash"],
                      ["NW Reek Hills ", [,], "/images/minefields/nwreekhillsminefield.jpg", "gutgash"],
                      ["East Cadavanaugh", [,], "/images/minefields/eastcadavanaughminefield.jpg", "gutgash"],
                      ["Central Cadavanaugh", [,], "/images/minefields/centralcadavanaughminefield.jpg", "gutgash"],
                      ["West Central Chalkies", [,], "/images/minefields/westcentralchalkiesminefield.jpg", "gutgash"],
                      ["East Central Chalkies ", [,], "/images/minefields/eastcentralchalkiesminefield.jpg", "gutgash"],
                      ["South Knit Sack", [,], "/images/minefields/southknitsackminefield.jpg", "pinkeye"],
                      ["SE Knit Sack", [,], "/images/minefields/seknitsackminefield.jpg", "pinkeye"],
                      ["South Rot 'N' Rusties", [,], "/images/minefields/southrotnrustiesminefield.jpg", "pinkeye"],
                      ["Central Rot 'N' Rusties", [,], "/images/minefields/centralrotnrustiesminefield.jpg", "pinkeye"],
                      ["Central Wailing Wind", [,], "/images/minefields/centralwailingwindminefield.jpg", "pinkeye"],
                      ["North Wailing Wind", [,], "/images/minefields/northwailingwindminefield.jpg", "pinkeye"],
                      ["South Central Grandrise", [,], "/images/minefields/southcentralgrandriseminefield.jpg", "pinkeye"],
                      ["East Central Grandrise", [,], "/images/minefields/eastcentralgrandriseminefield.jpg", "pinkeye"],
                      ["SE The Heights", [,], "/images/minefields/setheheightsminefield.jpg", "pinkeye"],
                      ["West The Heights", [,], "/images/minefields/westtheheightsminefield.jpg", "pinkeye"],
                      ["East The Dump", [,], "/images/minefields/eastthedumpminefield.jpg", "thedumps"], 
                                     ];

export const archangelsInfo = [["The Jack", "N/A", "Baby Bars", "Bantam V6", "Baby Exhaust", "Deep Treadies", "N/A",  "N/A",  "N/A", "Shovelface", "N/A"], 
                               ["Pinky Finger", "N/A", "N/A", "Major V6", "Big Buddy Exhaust", "Dual Groovies", "Frontier Springs",  "Ripperoni Rims",  "Front and Rear Barbs", "Die Rolla", "Racing Paint"],  
                               ["Celestial Bones", "N/A", "N/A", "Humongous V6", "N/A", "N/A", "N/A",  "N/A",  "N/A", "Furnace", "Gold Tar"],  
                               ["Soul Sweeper", "N/A", "Fracas Frame", "Major V6", "N/A", "Wide Treadies", "Little Guy Lift",  "Ripperoni Rims",  "Front and Rear Barbs", "Wild Hunt", "Raw Steel"],  
                               ["Kill Box", "Molition Grill", "N/A", "Major V6", "Big Buddy Exhaust", "N/A", "Frontier Springs",  "N/A",  "Rear Barbs", "Die Rolla", "N/A"],  
                               ["Righteous Spike", "N/A", "Big Buddy Bars", "Major V6", "Road Captain Exhaust", "N/A", "Frontier Springs",  "Grindmaster Rims",  "Whole Body Barbs", "Death Rattle", "Black Tar"],  
                               ["Speed Demon", "N/A", "N/A", "Massive V6", "Road Captain Exhaust", "Wide Treadies", "Frontier Springs",  "N/A",  "N/A", "Wild Hunt", "Raw Steel"],  
                               ["Sanguine Guardian", "Brawl Bar", "Big Buddy Bars", "Massive V6", "Road Captain Exhaust", "Sand Sliders", "N/A",  "N/A",  "N/A", "Furnace", "Primer"],  
                               ["Aurelian The Ready", "N/A", "Big Buddy Bars", "Humongous V6", "Road Captain Exhaust", "Slick Rubs", "Big Mama Lift Kit",  "Shredder Rims",  "N/A", "Death Rattle", "Gold Tar"],   
                               ["Argent Cavalier", "Two-Up Bump Bars", "Ferocious Frame", "Major Big Chief V8", "Big Buddy Exhaust", "Dual Groovies", "N/A",  "Ripperoni Rims",  "N/A", "Shovelface", "Raw Steel"],   
                               ["Rule of War", "N/A", "N/A", "Massive V6", "Big Buddy Exhaust", "Dune Cups", "Big Whammy Lift Kit",  "Grindmaster Rims",  "Whole Body Barbs", "Shovelface", "Primer"],   
                               ["Lord Gravel", "N/A", "N/A", "Bantam Big Chief V8", "President Exhaust", "Dune Cups", "Big Whammy Lift Kit",  "N/A",  "N/A", "Death Rattle", "Racing Paint"],   
                               ["Cardinal Grinder", "N/A", "Flimflam Frame", "Humongous Big Chief V8", "Road Captain Exhaust", "Dual Groovies", "The Major Lift",  "Shredder Rims",  "N/A", "Die Rolla", "Camouflage"],   
                               ["Radiant Shadow", "Clawjaw Kill Grill", "N/A", "Massive Big Chief V8", "Big Buddy Exhaust", "Dual Groovies", "Frontier Springs",  "N/A",  "N/A", "Furnace", "Black Tar"],   
                               ["Jugger of Virtue", "Clawjaw Kill Grill", "Ferocious Frame", "Humongous Big Chief V8", "President Exhaust", "Sand Sliders", "The Major Lift",  "N/A",  "Front and Rear Barbs", "Death Rattle", "Black Tar"],   
                               ["Speed Freak", "N/A", "N/A", "Ultimate Big Chief V8", "Baby Exhaust", "President Exhaust", "Slick Rubs",  "N/A",  "N/A", "Wild Hunt", "Raw Steel"], ];